#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/sync-release-inputs.sh [--check|--update]

Builds release-inputs/v1.textproto from the deployed xlsynth-crate
compatibility map, immutable upstream git tag targets, and the bytes of each
published dslx_stdlib.tar.gz. This is an out-of-band maintainer operation.

  --update  Replace the lock when generated bytes differ (default).
  --check   Exit non-zero when the checked-in lock differs.
USAGE
}

mode="update"
case "${1:-}" in
  "") ;;
  --update) mode="update" ;;
  --check) mode="check" ;;
  -h|--help) usage; exit 0 ;;
  *) echo "error: unknown argument: $1" >&2; usage >&2; exit 2 ;;
esac

for command in curl git jq sha256sum sort xargs awk sed; do
  if ! command -v "${command}" >/dev/null 2>&1; then
    echo "error: ${command} is required" >&2
    exit 2
  fi
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
compat_path="${repo_root}/third_party/xlsynth-crate/generated_version_compat.json"
output_path="${repo_root}/release-inputs/v1.textproto"
tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/xlsynth-release-inputs.XXXXXX")"
cleanup() {
  rm -rf "${tmp_dir}"
}
trap cleanup EXIT

jq -r 'to_entries[].value.xlsynth_release_version' "${compat_path}" |
  sed 's/^v//' |
  sort -V -u > "${tmp_dir}/versions.txt"

while IFS= read -r version; do
  if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$ ]]; then
    echo "error: invalid DSO version in compatibility map: ${version}" >&2
    exit 1
  fi
done < "${tmp_dir}/versions.txt"

git ls-remote --tags https://github.com/xlsynth/xlsynth.git > "${tmp_dir}/tags.txt"
mkdir -p "${tmp_dir}/archives"
xargs -P 8 -I VERSION sh -c '
  curl -fsSL --retry 3 --retry-delay 1     "https://github.com/xlsynth/xlsynth/releases/download/vVERSION/dslx_stdlib.tar.gz"     -o "$1/VERSION.tar.gz"
' _ "${tmp_dir}/archives" < "${tmp_dir}/versions.txt"

{
  echo '# SPDX-License-Identifier: Apache-2.0'
  echo
  echo 'record_version: 1'
  while IFS= read -r version; do
    base_ref="refs/tags/v${version}"
    commit="$(
      awk -v base_ref="${base_ref}" '
        $2 == base_ref { base = $1 }
        $2 == base_ref "^{}" { peeled = $1 }
        END { if (peeled != "") print peeled; else print base }
      ' "${tmp_dir}/tags.txt"
    )"
    if [[ ! "${commit}" =~ ^[0-9a-f]{40}$ ]]; then
      echo "error: could not resolve immutable commit for v${version}" >&2
      exit 1
    fi
    digest="$(sha256sum "${tmp_dir}/archives/${version}.tar.gz" | awk '{print $1}')"
    escaped_digest="$(printf '%s' "${digest}" | sed 's/../\\x&/g')"
    printf 'releases {\n'
    printf '  dso_version { value: "%s" }\n' "${version}"
    printf '  stdlib_tarball_sha256 { value: "%s" }\n' "${escaped_digest}"
    printf '  source_commit: "%s"\n' "${commit}"
    printf '}\n'
  done < "${tmp_dir}/versions.txt"
} > "${tmp_dir}/v1.textproto"

if cmp -s "${tmp_dir}/v1.textproto" "${output_path}"; then
  echo "release-input protobuf lock is up to date"
  exit 0
fi
if [[ "${mode}" == "check" ]]; then
  echo "release-input protobuf lock is out of date; run scripts/sync-release-inputs.sh --update" >&2
  exit 1
fi
mkdir -p "$(dirname "${output_path}")"
cp "${tmp_dir}/v1.textproto" "${output_path}"
echo "updated release-input protobuf lock at ${output_path}"
